/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
}

repositories {
    mavenLocal()
    mavenCentral()

    maven("https://hub.spigotmc.org/nexus/content/repositories/public/")
    maven("https://repo.mikigal.pl/releases")
    maven("https://maven.enginehub.org/repo/")
}

dependencies {
    compileOnly(libs.org.jetbrains.annotations)
    implementation(libs.pl.mikigal.configapi)
    compileOnly(libs.org.spigotmc.spigot.api)
    compileOnly(libs.com.sk89q.worldedit.worldedit.bukkit)
}

group = "ru.morozovit"
version = "1.0-SNAPSHOT"
description = "BedwarsPlugin"

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc> {
    options.encoding = "UTF-8"
}


tasks.withType<Jar> {
    from(
        configurations.runtimeClasspath
        .get()
        .files
        .map { if (it.isDirectory) it else zipTree(it) }
    )

    destinationDirectory = file("server/plugins")
}

tasks.register<Exec>("run") {
    dependsOn("jar")
    workingDir = file("server")
    commandLine("/bin/bash", "$rootDir/server/start.sh")
}